# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(380, 324)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.price = QtWidgets.QLabel(self.gridLayoutWidget)
        self.price.setObjectName("price")
        self.gridLayout.addWidget(self.price, 5, 0, 1, 1)
        self.id = QtWidgets.QLabel(self.gridLayoutWidget)
        self.id.setObjectName("id")
        self.gridLayout.addWidget(self.id, 0, 0, 1, 1)
        self.descrip = QtWidgets.QLabel(self.gridLayoutWidget)
        self.descrip.setObjectName("descrip")
        self.gridLayout.addWidget(self.descrip, 4, 0, 1, 1)
        self.sort = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sort.setObjectName("sort")
        self.gridLayout.addWidget(self.sort, 1, 0, 1, 1)
        self.id_lbl = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.id_lbl.setObjectName("id_lbl")
        self.gridLayout.addWidget(self.id_lbl, 0, 1, 1, 1)
        self.roast = QtWidgets.QLabel(self.gridLayoutWidget)
        self.roast.setObjectName("roast")
        self.gridLayout.addWidget(self.roast, 2, 0, 1, 1)
        self.ground = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ground.setObjectName("ground")
        self.gridLayout.addWidget(self.ground, 3, 0, 1, 1)
        self.volume = QtWidgets.QLabel(self.gridLayoutWidget)
        self.volume.setObjectName("volume")
        self.gridLayout.addWidget(self.volume, 6, 0, 1, 1)
        self.sort_lbl = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.sort_lbl.setObjectName("sort_lbl")
        self.gridLayout.addWidget(self.sort_lbl, 1, 1, 1, 1)
        self.roast_lbl = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.roast_lbl.setObjectName("roast_lbl")
        self.gridLayout.addWidget(self.roast_lbl, 2, 1, 1, 1)
        self.ground_lbl = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ground_lbl.setObjectName("ground_lbl")
        self.gridLayout.addWidget(self.ground_lbl, 3, 1, 1, 1)
        self.descrip_lbl = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.descrip_lbl.setObjectName("descrip_lbl")
        self.gridLayout.addWidget(self.descrip_lbl, 4, 1, 1, 1)
        self.price_lbl = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.price_lbl.setObjectName("price_lbl")
        self.gridLayout.addWidget(self.price_lbl, 5, 1, 1, 1)
        self.volume_lbl = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.volume_lbl.setObjectName("volume_lbl")
        self.gridLayout.addWidget(self.volume_lbl, 6, 1, 1, 1)
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setGeometry(QtCore.QRect(150, 290, 75, 23))
        self.save_btn.setObjectName("save_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add/Edit item"))
        self.price.setText(_translate("Form", "Price"))
        self.id.setText(_translate("Form", "ID"))
        self.descrip.setText(_translate("Form", "Description"))
        self.sort.setText(_translate("Form", "Sort"))
        self.roast.setText(_translate("Form", "Roast degree"))
        self.ground.setText(_translate("Form", "Ground / Beans"))
        self.volume.setText(_translate("Form", "Volume"))
        self.save_btn.setText(_translate("Form", "Save"))
